#!/bin/bash

if [ $# -eq 0 ]; then
  explorer.exe .
else
  if [ -e $1 ]; then
    cmd.exe /c start $(wslpath -w $1) 2>/dev/null
  else
    echo "open: $1 : No such file or directory"
    exit 1
  fi
fi
exit 0
